services:
  - type: worker
    name: note-ticketing-bot
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: DISCORD_TOKEN
        sync: false # Set in Render dashboard
      - key: APPLICATION_ID
        sync: false # Set in Render dashboard
      - key: WEBHOOK_URL
        sync: false # Set in Render dashboard 